### ISSUE TITLE
Dont call path.resolve

### ISSUE THREAD

**Issue by felixfbecker** [sindresorhus/file-url#2]
I need to construct file URLs for a Linux system in a script running on Windows. When I do this:

``` js
fileUrl('/test/test.txt')
```

results in 

```
file://c:/test/text.txt
```

Which is totally wrong of course. The C drive letter comes from path.resolve, which resolves relative to the cwd.

Please either remove this or add a parameter to turn it off

**Comment by sindresorhus** [comment]
What would be the expected output?

Please see https://en.wikipedia.org/wiki/File_URI_scheme

**Comment by felixfbecker** [comment]
Of course `file:///test/test.txt`

**Comment by felixfbecker** [comment]
This function should not assume that the input is a local windows path when running on Windows. I might run on Windows, but pass in a Linux path. The output should be a Linux file URL then, and not contain any magic drive letters.

**Comment by felixfbecker** [comment]
Maybe a clearer example: `fileUrl('/var/www/index.html')` should return `file:///var/www/index.html`, but on a Windows system it returns `file:///c:/var/www/index.html` because of the path.resolve()

**Comment by sindresorhus** [comment]
But `file:///var/www/index.html` wouldn't work on Windows AFAIK. So not really sure what you're trying to do here. I'm using `path.resolve()` since it's normal to be able to pass a relative path to path accepting functions in Node.js.

**Comment by felixfbecker** [comment]
Use case: I have a debug adapter for Visual Studio Code and PHP XDebug. One feature is to be able to debug remote hosts, so VS Code runs on your PC (which might be Windows) while the webserver is running on a server (which might be Linux). Visual Studio Code always talks file paths, while XDebug always talks file URLs. So I need to convert the paths to file URLs. It is a bit more complicated, I need to find out relative bits and adapt paths, but this is not relevant. In the end, I have the file path on the server (which might be a Linux path), and need to convert it to a file URL. But when I try to convert it in the adapter, which always runs on the PC (which might be Windows), the drive letter is magically added.

**Comment by sindresorhus** [comment]
I guess we could do like [Node.js core](https://nodejs.org/api/path.html#path_path_win32) and have a `fileUrl.posix()` and `fileUrl.win()` submethods, that forces the path handling regardless of current OS. PR welcome.

**Comment by felixfbecker** [comment]
> I'm using path.resolve() since it's normal to be able to pass a relative path to path accepting functions in Node.js.

I would strongly disagree with that. If I pass in a relative path to this function, I expect a relative URL out - not something that got magically resolved relative to the cwd.

> I guess we could do like Node.js core and have a fileUrl.posix() and fileUrl.win() submethods, that forces the path handling regardless of current OS. PR welcome.

Thats the point. I cannot _know_ if the server is a Linux server or a Windows server, so I cannot choose either `.posix` or `.win32`.

The expected behavior of this function is that it takes a path in and puts a file URL out, no matter what OS I'm on or what the cwd is. If users want to resolve the path to the cwd, they can call path.resolve beforehand. But this is not what this function should do.

**Comment by sindresorhus** [comment]
> I expect a relative URL out - not something that got magically resolved relative to the cwd.

Looked into this and turns out File URLs must be absolute. See: http://stackoverflow.com/a/15193744/64949

> Thats the point. I cannot know if the server is a Linux server or a Windows server, so I cannot choose either .posix or .win32.

But `fileUrl.posix('/test/test.txt')` would result in `file:///test/test.txt` regardless of OS.

**Comment by felixfbecker** [comment]
Relative url was just an example, a bad one admittedly. The real issue still is that this function resolves paths dependent on the machine it is executed on, which leads to unexpected results when passing paths from other machines, that may or may not have a different OS.

`fileUrl.posix` doesn't make any sense...
- what would that function output when passed a Windows path? As I said I cannot know what the other machine's OS is
- even when using `fileUrl.posix`, I assume you would still call `path.posix.resolve`, which means the path still gets resolved to the local cwd, which is simply semantically wrong if the path originates from another machine

If you want to keep the current behavior on by default, please just add a second boolean parameter `resolve`, and if I pass `false` to this, don't call `path.resolve`.

**Comment by sindresorhus** [comment]
I disagree, but I'm open to adding a `resolve` option that is `true` by default.

**Comment by felixfbecker** [comment]
@sindresorhus Thank you :)
