### ISSUE TITLE
Why does this have a massive meow dependency?

### ISSUE THREAD

**Issue by domenic** [sindresorhus/file-url#4]
It seems unusued and is really bloating my node_modules directory. I was hoping to just reuse the logic in this package instead of rolling my own, but I don't want to drag along all of

```
  | `-- meow@3.7.0
  |   +-- camelcase-keys@2.1.0
  |   | `-- camelcase@2.1.1
  |   +-- loud-rejection@1.6.0
  |   | +-- currently-unhandled@0.4.1
  |   | | `-- array-find-index@1.0.2
  |   | `-- signal-exit@3.0.1
  |   +-- map-obj@1.0.1
  |   +-- minimist@1.2.0
  |   +-- normalize-package-data@2.3.5
  |   | +-- hosted-git-info@2.1.5
  |   | +-- is-builtin-module@1.0.0
  |   | | `-- builtin-modules@1.1.1
  |   | +-- semver@5.3.0
  |   | `-- validate-npm-package-license@3.0.1
  |   |   +-- spdx-correct@1.0.2
  |   |   | `-- spdx-license-ids@1.2.2
  |   |   `-- spdx-expression-parse@1.0.4
  |   +-- object-assign@4.1.0
  |   +-- redent@1.0.0
  |   | +-- indent-string@2.1.0
  |   | | `-- repeating@2.0.1
  |   | |   `-- is-finite@1.0.2
  |   | `-- strip-indent@1.0.1
  |   |   `-- get-stdin@4.0.1
  |   `-- trim-newlines@1.0.0
```

just to do 20 lines of string processing.

**Comment by SamVerschueren** [comment]
Good point. Normally the API and cli are separated for example [trash](https://github.com/sindresorhus/trash) and [trash-cli](https://github.com/sindresorhus/trash-cli). This one seems to be forgotten.

@sindresorhus Let me know if you want me to separate it or if you have some time to do it.

**Comment by SamVerschueren** [comment]
That was fast :)

**Comment by domenic** [comment]
Thank you! I didn't realize this even had a CLI.

**Comment by sindresorhus** [comment]
No problem. I thought I had extracted all my CLI's, but must have missed this one. Yeah, [that's one of the reasons](https://github.com/sindresorhus/ama/issues/17) I tend to put CLI's in separate packages now. That and less dependencies.
