### ISSUE TITLE
Not all special characters are escaped correctly

### ISSUE THREAD

**Issue by jorangreef** [sindresorhus/file-url#7]
`file-url` does not escape paths containing `&`, `=` and `:` correctly.

**Comment by sindresorhus** [comment]
Can you provide an example input and output that is incorrect? Or even better a [failing test](https://github.com/avajs/ava#failing-tests)?

**Comment by jorangreef** [comment]
I think this should remain open? I don't think there has been any fix or test for this?

The example input which needs to be escaped (`&`, `=` and `:`) has already been provided.
